name: Prolog tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install SWI-Prolog
        run: |
          sudo apt-get update
          sudo apt-get install --yes software-properties-common
          sudo add-apt-repository ppa:swi-prolog/stable
          sudo apt-get update
          sudo apt-get install --yes swi-prolog-nox

      - name: Check SWI-Prolog
        run: |
          swipl --version
          swipl -g "current_prolog_flag(version_data, V), writeln(V)" -t halt

      - name: Install s(CASP)
        run: |
          sudo mkdir -p /usr/lib/swi-prolog/bin/bin
          swipl -g "pack_install(scasp, [interactive(false)])" -t halt

      - name: Run plunit suite
        run: |
          swipl -g run_tests -t halt tests/*.pl