name: Prolog tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install SWI-Prolog
        run: |
          sudo apt-get update
          sudo apt-get install --yes swi-prolog-nox
      - name: Install s(CASP)
        run: swipl -g "pack_install(scasp, [interactive(false)])" -t halt
      - name: Run plunit suite
        run: swipl -g run_tests -t halt tests/*.pl
